apply plugin: "java"

sourceSets.main.java.srcDirs = [ "src/" ]
sourceSets.main.resources.srcDirs = ["../util/resources"]

project.ext.mainClassName = "net.krusher.laffsoccer.util.GenerateTeam"
project.ext.assetsDir = new File("../assets")

tasks.register('run', JavaExec) {
  dependsOn classes
  main = project.mainClassName
  classpath = sourceSets.main.runtimeClasspath
  standardInput = System.in
  workingDir = project.assetsDir
  ignoreExitValue = true
}

tasks.register('debug', JavaExec) {
  dependsOn classes
  main = project.mainClassName
  classpath = sourceSets.main.runtimeClasspath
  standardInput = System.in
  workingDir = project.assetsDir
  ignoreExitValue = true
  debug = true
}

dependencies {
  // https://mvnrepository.com/artifact/org.jsoup/jsoup
  implementation("org.jsoup:jsoup:1.22.1")
  // https://mvnrepository.com/artifact/commons-io/commons-io
  implementation("commons-io:commons-io:2.21.0")
  implementation project(":core")
}
