[compileJava, compileTestJava]*.options*.encoding = 'UTF-8'
eclipse.project.name = appName + '-core'

dependencies {
  api "com.badlogicgames.gdx-controllers:gdx-controllers-core:$gdxControllersVersion"
  api "com.badlogicgames.gdx:gdx:$gdxVersion"
  api "com.esotericsoftware:kryonet:$kryoNetVersion"

  if(enableGraalNative == 'true') {
    implementation "io.github.berstanio:gdx-svmhelper-annotations:$graalHelperVersion"
  }

  implementation group: 'ar.com.hjg', name: 'pngj', version: '2.1.0'
  implementation "com.strongjoshua:libgdx-inGameConsole:1.0.0"
}
jar {
  duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}
