name: Build MacOS LWJGL3

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      - name: Ejecutar Gradle (LWJGL3 MacosM1)
        working-directory: java
        run: ./gradlew lwjgl3:laffDistMacARM64 --no-daemon --console=plain --info

      - name: Build Mac .app con jpackage
        working-directory: java
        run: |
          # Leer la versión del proyecto desde gradle.properties
          projectVersion=$(grep '^projectVersion=' gradle.properties | cut -d'=' -f2)
          echo "Project version: $projectVersion"
          
          # Si empieza por 0., cambiar por 1.
          if [[ "$projectVersion" == 0.* ]]; then
            macVersion="1.${projectVersion#0.}"
          else
            macVersion="$projectVersion"
          fi

          # Directorio de salida
          APP_OUTPUT="release/Charnego Internatiolaff Soccer.app"
          mkdir -p "$APP_OUTPUT"

          # JAR principal generado por Gradle
          MAIN_JAR="LaffSoccer-${projectVersion}.jar"

          # Confirmar que existe
          ls lwjgl3/build/libs/$MAIN_JAR

          # Ejecutable .app con jpackage
          jpackage \
            --type app-image \
            --name "Charnego Internatiolaff Soccer" \
            --input lwjgl3/build/libs \
            --main-jar "$MAIN_JAR" \
            --main-class "com.ygames.ysoccer.lwjgl3.Lwjgl3Launcher" \
            --icon lwjgl3/icons/logo.png \
            --app-version "$macVersion" \
            --dest "$APP_OUTPUT" \
            --runtime-image "$JAVA_HOME"
          # Mostrar la ruta absoluta de la app generada
          echo "La .app se ha generado en la ruta absoluta:"
          realpath "$APP_OUTPUT"

      - name: Publicar artefacto
        uses: actions/upload-artifact@v4
        with:
          name: laff-soccer-macos
          path: release